pool: nav-prod
config:
  cleanupPolicy: compact
  minimumInSyncReplicas: 1
  partitions: 1
  replication: 3
  retentionBytes: -1
  retentionHours: 720
acl:
  - team: k9saksbehandling
    application: k9-klage
    access: read
