apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: vedtak-fattet.v1
  namespace: klage
  labels:
    team: klage
spec:
  pool: {{pool}}
  config:
  {{#each config as |value key|}}
     {{key}}: {{value}}
  {{/each}}
  acl:
    - team: klage
      application: kabal-api
      access: write
    - team: k9saksbehandling
      application: k9-klage
      access: read
