spring:
  main:
    banner-mode: OFF
  sleuth:
    propagation-keys:
      - Nav-Callid
      - Nav-Consumer-Id
    log:
      slf4j:
        whitelisted-mdc-keys:
          - Nav-Callid
          - Nav-Consumer-Id
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

server:
  port: 7081
  error:
    whitelabel:
      enabled: false

management:
  endpoint:
    health:
      show-details: always
  endpoints.web:
    exposure:
      include: info, health, metrics, prometheus
    base-path: "/internal"
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

SERVICE_USER_USERNAME: srvklage-saksbeh

TENANT_ID: 966ac572-f5b7-4bbe-aa88-c76419c0f851

no.nav.security.jwt:
  issuer:
    aad:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${AZURE_APP_CLIENT_ID}
  client:
    registration:
      azure-onbehalfof:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: https://graph.microsoft.com/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      oppgave-onbehalfof:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
        scope: api://7380b8f7-ab50-4b47-8006-3df014946590/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      app:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: https://graph.microsoft.com/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic

navCallId: Nav-Callid
navConsumerId: Nav-Consumer-Id

allowed.origins:
  https://klage-oppgave.nav.no,
  https://klage-oppgave.dev.nav.no

AXSYS_URL: https://api-gw-q1.oera.no/axsys/api/v1/tilgang
MICROSOFT_GRAPH_URL: https://graph.microsoft.com/v1.0
OPPGAVE_URL_Q1: https://api-gw-q1.oera.no/oppgave/api/v1/oppgaver
OPPGAVE_URL_Q2: https://api-gw-q2.oera.no/oppgave/api/v1/oppgaver
UNLEASH_URL: https://unleash.nais.io/api/