TENANT_ID: 62366534-1ec3-4962-8869-9b5535279d0b
SECURITY_TOKEN_SERVICE_REST_URL: https://api-gw.oera.no/security-token-service
PDL_BASE_URL: https://api-gw.oera.no/pdl-api/graphql

NORG2_API_V1_URL: https://api-gw.oera.no/norg2/api/v1
PROXY_APP_CLIENT_ID: 981be1fb-1379-465f-bddc-7563197aed84

OPPGAVE_APP_CLIENT_ID: 50346823-61a0-49e7-ad89-ea2b1a0e90f8

KLAGEPROXY_URL: https://klage-fss-proxy.prod-fss-pub.nais.io

OPPGAVE_URL: https://api-gw.oera.no/oppgave/api/v1/oppgaver

AXSYS_URL: https://api-gw.oera.no/axsys/api/v1

KAFKA_BOOTSTRAP_SERVERS: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
KAFKA_SCHEMA_REGISTRY_URL: https://kafka-schema-registry.nais.adeo.no/

SAF_BASE_URL: https://saf.nais.adeo.no/graphql
SAF_APP_CLIENT_ID: feb9588b-a3d6-4d2f-8809-97284046ae72