apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: vedtak-fattet
  namespace: klage
  labels:
    team: klage
  annotations:
    dcat.data.nav.no/title: "Vedtak fattet på klage"
    dcat.data.nav.no/description: "Fullførte vedtak på klageinstans som er klare for førsteinstans postes på dette topicet."
spec:
  pool: nav-dev
  config:  # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 72  # -1 means unlimited
  acl:
    - team: klage
      application: klage-oppgave-api
      access: readwrite
