apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: vedtak-fattet
  namespace: klage
  labels:
    team: klage
  annotations:
    dcat.data.nav.no/title: "Vedtak fattet på klage"
    dcat.data.nav.no/description: "Fullførte vedtak på klageinstans som er klare for førsteinstans postes på dette topicet."
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 720
  acl:
    - team: klage
      application: kabal-api
      access: readwrite
