name: End-to-end tests

on:
  workflow_dispatch:

jobs:
  acceptance-tests:
    name: Run acceptance tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: navikt/kabal-api
      - name: Run acceptance tests
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_API_KEY }}
          IMAGE: docker.pkg.github.com/navikt/klage-oppgave-e2e/klage-oppgave-e2e:latest
          CLUSTER: dev-gcp
          VAR: app=klage-oppgave
          TEAM: klage
          RESOURCE: deploy/e2ejob.yml
          VARS: deploy/dev.yaml
        timeout-minutes: 5
