name: Deploy kafka topics

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: deploy to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_API_KEY }}
          CLUSTER: dev-gcp
          RESOURCE: kafka-aiven/vedtak-fattet.v1/topic.yaml
          VARS: kafka-aiven/vedtak-fattet.v1/dev-vars.yaml
          PRINT_PAYLOAD: true
      - name: deploy to prod
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_API_KEY }}
          CLUSTER: prod-gcp
          RESOURCE: kafka-aiven/vedtak-fattet.v1/topic.yaml
          VARS: kafka-aiven/vedtak-fattet.v1/prod-vars.yaml
          PRINT_PAYLOAD: true
